#ifndef _LD3320_CONFIG_H__
#define _LD3320_CONFIG_H__

///识别码

#define CODE_RECOGNIZE_FAILURE				0
#define CODE_AIR_CONDITIONER_ON				1
#define CODE_AIR_CONDITIONER_OFF			2
#define CODE_LIVING_ROOM_LIGHT_ON			3
#define CODE_LIVING_ROOM_LIGHT_OFF			4
#define CODE_BEDROOM_LIGHT_ON				5
#define CODE_BEDROOM_LIGHT_OFF				6
#define CODE_DOOR_OPEN						7
#define CODE_DOOR_CLOSE						8
#define CODE_WINDOW_OPEN					9
#define CODE_WINDOW_CLOSE					10
#define CODE_GARBAGE 						11
#define CODE_NI_MEI 						12

///LD3320引脚相关定义
#define LD3320RST_PIN			GPIO_Pin_5		
#define LD3320RST_GPIO_PORT		GPIOC
#define LD3320RST_GPIO_CLK		RCC_APB2Periph_GPIOC
#define LD_RST_H() 				GPIO_SetBits(GPIOC, GPIO_Pin_5)
#define LD_RST_L() 				GPIO_ResetBits(GPIOC, GPIO_Pin_5)

#define LD3320CS_PIN			GPIO_Pin_1	
#define LD3320CS_GPIO_PORT		GPIOA
#define LD3320CS_GPIO_CLK		RCC_APB2Periph_GPIOA
#define LD_CS_H()				GPIO_SetBits(GPIOA, GPIO_Pin_1)
#define LD_CS_L()				GPIO_ResetBits(GPIOA, GPIO_Pin_1)

#define LD3320IRQ_GPIO_CLK		RCC_APB2Periph_GPIOD
#define LD3320IRQ_PIN			GPIO_Pin_2
#define LD3320IRQ_GPIO_PORT		GPIOD
#define LD3320IRQEXIT_PORTSOURCE		GPIO_PortSourceGPIOD

#define LD3320IRQPINSOURCE	    	GPIO_PinSource2
#define LD3320IRQEXITLINE			EXTI_Line2
#define LD3320IRQN					 EXTI2_IRQn 	//	EXTI15_10_IRQn 

#define LD3320WR_PIN					GPIO_Pin_4
#define LD3320WR_GPIO_PORT		GPIOC
#define LD3320WR_GPIO_CLK		RCC_APB2Periph_GPIOC
#define LD_SPIS_H()  			GPIO_SetBits(GPIOC, GPIO_Pin_4)
#define LD_SPIS_L()  			GPIO_ResetBits(GPIOC, GPIO_Pin_4)

#define	LD3320SPI							SPI1
#define LD3320SPI_CLK					RCC_APB2Periph_SPI1						

#define LD3320SPIMISO_PIN			GPIO_Pin_6
#define LD3320SPIMISO_GPIO_PORT		GPIOA
#define LD3320SPIMISO_GPIO_CLK		RCC_APB2Periph_GPIOA

#define LD3320SPIMOSI_PIN					GPIO_Pin_7
#define LD3320SPIMOSI_GPIO_PORT		GPIOA
#define LD3320SPIMOSI_GPIO_CLK		RCC_APB2Periph_GPIOA

#define LD3320SPISCK_PIN			GPIO_Pin_5
#define LD3320SPISCK_GPIO_PORT		GPIOA
#define LD3320SPISCK_GPIO_CLK		RCC_APB2Periph_GPIOA
#endif
